// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVW9djicLQLHTURbKN6ePFuVubRF9-PZs',
    appId: '1:737404799154:web:3c298734b9edaa3ccf21ab',
    messagingSenderId: '737404799154',
    projectId: 'ecommerceapp-7af6c',
    authDomain: 'ecommerceapp-7af6c.firebaseapp.com',
    storageBucket: 'ecommerceapp-7af6c.firebasestorage.app',
    measurementId: 'G-FF4TC874HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_z6gIr9eVB_5pw3nHZlDL_SMmkVDx0wU',
    appId: '1:737404799154:android:98199041329fa542cf21ab',
    messagingSenderId: '737404799154',
    projectId: 'ecommerceapp-7af6c',
    storageBucket: 'ecommerceapp-7af6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL5ruphMoHgGRS7hoopBlLH-bHx0a4UTo',
    appId: '1:737404799154:ios:312a201d6bc29fdbcf21ab',
    messagingSenderId: '737404799154',
    projectId: 'ecommerceapp-7af6c',
    storageBucket: 'ecommerceapp-7af6c.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVW9djicLQLHTURbKN6ePFuVubRF9-PZs',
    appId: '1:737404799154:web:18402cf2f433851acf21ab',
    messagingSenderId: '737404799154',
    projectId: 'ecommerceapp-7af6c',
    authDomain: 'ecommerceapp-7af6c.firebaseapp.com',
    storageBucket: 'ecommerceapp-7af6c.firebasestorage.app',
    measurementId: 'G-NBFR8RZ568',
  );
}
